"""initial schema

Revision ID: 771648d37cfd
Revises: 
Create Date: 2026-08-25 17:44:00.831225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771648d37cfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'city', 'state', name='uq_course_name_location')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('handicap_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_on', sa.Date(), nullable=False),
    sa.Column('index_value', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'effective_on', name='uq_snapshot_user_date')
    )
    op.create_index(op.f('ix_handicap_snapshots_user_id'), 'handicap_snapshots', ['user_id'], unique=False)
    op.create_table('tees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('course_rating', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('slope_rating', sa.Integer(), nullable=False),
    sa.Column('yardage', sa.Integer(), nullable=True),
    sa.CheckConstraint('course_rating > 0', name='ck_tee_course_rating_positive'),
    sa.CheckConstraint('par > 0', name='ck_tee_par_positive'),
    sa.CheckConstraint('slope_rating BETWEEN 55 AND 155', name='ck_tee_slope_in_whs_range'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', name='uq_tee_course_name')
    )
    op.create_index(op.f('ix_tees_course_id'), 'tees', ['course_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tee_id', sa.Integer(), nullable=False),
    sa.Column('played_on', sa.Date(), nullable=False),
    sa.Column('gross_score', sa.Integer(), nullable=False),
    sa.Column('index_at_time', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('pcc', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_nine_hole', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gross_score > 0', name='ck_round_score_positive'),
    sa.CheckConstraint('pcc BETWEEN -1 AND 3', name='ck_round_pcc_in_whs_range'),
    sa.ForeignKeyConstraint(['tee_id'], ['tees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_tee_id'), 'rounds', ['tee_id'], unique=False)
    op.create_index(op.f('ix_rounds_user_id'), 'rounds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_user_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_tee_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_tees_course_id'), table_name='tees')
    op.drop_table('tees')
    op.drop_index(op.f('ix_handicap_snapshots_user_id'), table_name='handicap_snapshots')
    op.drop_table('handicap_snapshots')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
