"""drop handicap index storage

The app stopped computing a Handicap Index, so it stops storing one. Typical and
potential are quantiles of a golfer's own Score Differentials, and a differential
is a function of the score, the rating, the slope and the PCC alone -- no index
enters the chain at any point. See the module docstring in golf/handicap.py.

Two objects go:

  handicap_snapshots     held the OFFICIAL index from a handicap service, so the
                         app's figure could be shown against it. With no figure
                         of ours to compare, nothing reads it.
  rounds.index_at_time   held the index in effect on the day, to keep past rounds
                         from being regraded against today's number. Point-in-time
                         correctness now comes from played_on instead: the API
                         grades each round on the rounds played before it.

This is destructive and the downgrade cannot undo it. Reversing recreates the
table and the column empty -- the values themselves are gone.

Revision ID: f0af46a77733
Revises: 771648d37cfd
Create Date: 2026-08-26 02:35:35.877095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0af46a77733'
down_revision: Union[str, Sequence[str], None] = '771648d37cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handicap_snapshots_user_id'), table_name='handicap_snapshots')
    op.drop_table('handicap_snapshots')
    op.drop_column('rounds', 'index_at_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('index_at_time', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.create_table('handicap_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('effective_on', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('index_value', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('handicap_snapshots_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('handicap_snapshots_pkey')),
    sa.UniqueConstraint('user_id', 'effective_on', name=op.f('uq_snapshot_user_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_handicap_snapshots_user_id'), 'handicap_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###
